### ISSUE TITLE
housing friend list popup

### ISSUE THREAD

**Issue by OntheDOL** [Los-Ojos/DOLSharp-1124#42]
Housing friend list / permission list seems to randomly popup while dual logging characters occasionally.

Hard to reproduce so i havent been able to track it down just yet

**Comment by OntheDOL** [comment]
Pretty big bug actually. When this happens, the server has been sending packets with a random header from 01 to 10 . When its sent as 03 or 05 , housing permission packets, the resulting permission window pops up on the client. These are normally only sent from the server after being requested by the client by clicking on the housing permission buttons. 
I'm pretty sure this doesn't happen on official DOL repo, though I also don't think anything has changed in the actual packet sending code on this repo.

**Comment by Eyeblaze** [comment]
Not happening on official DOL repo after several testings. (new Download+compile, new gameclient (1.109))
More testings running atm. will post further feedback soon.

**Comment by OntheDOL** [comment]
I've never been able to reproduce this bug since , leading me to believe this was something to do with an older version , possibly modified.

**Comment by OntheDOL** [comment]
After hearing this was still an issue i re-investigated and found that a minimum of 3 clients was needed to reproduce it. Bug in code was tracked down and should be fixed after next merge.
